# External Gems
gems: 						[jekyll-paginate]


# Site Settings
title: 						"Victor S. Wang"
email: 						"wangshengjia01@gmail.com"
description: 		  "My Blog"
baseurl: 					""
homeurl: 					"http://allblue.me"
logourl: 					"/assets/img/bloglogo.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 				5
encoding: utf-8

# Author Settings
author_name: 				"Victor S. Wang"
author_url: 				"www.allblue.me"
author_bio: 		    "startup, freelancer, developer, technology enthusiasts, innovation, passion"
author_email: 			"wangshengjia01@gmail.com"
author_image: 			"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/wangshengjia"
github_url:  				"http://github.com/wangshengjia"
linkedin_url:  				"https://fr.linkedin.com/in/shengjiawang"

# Theme Settings
theme_disqus_shortname: 	"Victor"
theme_google_comments: 		false
theme_analytics_id: 		"UA-72234238-1"
theme_analytics_domain: ""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
permalink: 					pretty

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
